# Auto-Generated by /home/furiousdroid/android/lineage22/device/samsung/universal7885-common/generate_product_makefiles.py
$(call inherit-product, device/samsung/jackpotlte/full_jackpotlte.mk)
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)

PRODUCT_NAME := lineage_jackpotlte

TARGET_BOOT_ANIMATION_RES := 1080
TARGET_USES_MINI_GAPPS := true
